[project]
name = "dreamer-v3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "filelock==3.20.0",
    "fsspec==2025.12.0",
    "jinja2==3.1.6",
    "markupsafe==3.0.2",
    "mpmath==1.3.0",
    "networkx==3.6.1",
    "numpy==2.4.0rc1",
    "pillow==12.0.0",
    "setuptools==78.1.0",
    "sympy==1.14.0",
    "torch==2.11.0.dev20260204+rocm7.1",
    "triton-rocm==3.6.0+git9844da95",
    "torchvision==0.25.0.dev20260205+rocm7.1",
    "typing-extensions==4.15.0",
]

[tool.uv]
prerelease = "allow"

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/nightly/rocm7.1"
explicit = false
[tool.uv.sources]
torch = { index = "pytorch-rocm" }
torchvision = { index = "pytorch-rocm" }
